### ISSUE TITLE
use information from osmdata to get location information

### ISSUE THREAD

**Issue by njtierney** [njtierney/maxcovr#48]
https://ropensci.github.io/osmdata/

**Comment by njtierney** [comment]
I think I was curious whether this could return building / site location information that would help in choosing facilities. So, say I wanted to build a police station or place a phone tower, could I use this to help me find GPS coords of buildings/properties? 

CC @mpadge

**Comment by mpadge** [comment]
Yep, but very dependent on quality of info. In the UK, you should be good to go. I'm currently working on projects in Kathmandu, in which buildings are very well mapped (earthquakes have that effect these days), and Accra, which is comparably terribly mapped (for buildings) so `osmdata` gives nowt there. You just won't be able to assume any methods developed like this will necessarily be globally applicable.

**Comment by njtierney** [comment]
Thanks for that, Mark! I think that this example then would perhaps be best worked into the vignette / paper that you suggested in #55, so I'm going to close this issue, but I'm happy to reopen it if you'd like :)
