### ISSUE TITLE
namespace in max_coverage

### ISSUE THREAD

**Issue by carbonmetrics** [njtierney/maxcovr#65]
max_coverage does not run without loading dplyr. 
max_coverage contains function extract_mc_results in line 156,
and that function calls bind_rows in line 45 - I guess dplyr::bind_rows would solve the issue.

as an aside - why did you implement this in dplyr? data.table is *much* faster.

**Comment by njtierney** [comment]
Hello!

Thank you for picking up on the namespace issue! This has now been fixed.

I am interested in making `maxcovr` faster in the future, `data.table` will be considered at a later release (#68), but for the moment there are other changes that I would like to make. I would welcome a PR for using data.table if you are interested
