### ISSUE TITLE
distance calculation

### ISSUE THREAD

**Issue by carbonmetrics** [njtierney/maxcovr#67]
This is more a clarification than an issue: what coordinate system are you using? Are you always expecting WGS84?

**Comment by njtierney** [comment]
Hello, 

The distance is calculated using [haversines formula](https://en.wikipedia.org/wiki/Haversine_formula), which makes the assumption that the earth is a sphere - whilst not wholly correct, it is a useful approximation that is reasonable for small scale distances (1-10km), which is what `maxcovr` was initially built for.

In the future `maxcovr` will use more accurate distance functions provided in [`geodist`](https://github.com/hypertidy/geodist). I found [this thread](https://gis.stackexchange.com/questions/162609/which-spatial-reference-system-is-used-by-the-haversine-formula) useful when understanding this problem.

I've added a note into the README under [Known Issues](https://github.com/njtierney/maxcovr#known-issues) - I am glad you raised this issue!

Thank you for your inputs!
